### ISSUE TITLE
Color samples styled differently

### ISSUE THREAD

**Issue by waldyrious** [fiatjaf/rosetta.alhur.es#3]
Is this intended?

![screenshot](https://cloud.githubusercontent.com/assets/478237/15739344/895bd2b8-28a7-11e6-99cf-9d9c6ac7e4d7.png)

**Comment by fiatjaf** [comment]
Yes, I just load two difference code-highlighting libraries and let they do their job. Reading their docs, I found that what one does support the other doesn't, so we get to this point.

I would prefer to have a single library doing the job. Do you know what could we use for that?

**Comment by waldyrious** [comment]
I never looked into code-highlighting libraries, sorry. I've heard a few names over the years (mediawiki uses GheSHi, I've heard people speak well of pygments and highlight.js...), but I'm not sure how they compare or even what your requirements are. In any case, I'm glad this is a known issue and not a bug that shouldn't be happening :)

**Comment by fiatjaf** [comment]
Ok, that's good, then. I'm going to close this issue until someone comes up with a better solution.
