### ISSUE TITLE
Comparing C++ and D fails

### ISSUE THREAD

**Issue by waldyrious** [fiatjaf/rosetta.alhur.es#4]
http://rosetta.alhur.es/compare/D/C++/

This seems to be an issue with "C++", because e.g. http://rosetta.alhur.es/compare/D/J/ works, but http://rosetta.alhur.es/compare/C++/J/ doesn't.

**Comment by fiatjaf** [comment]
The problem probably is happening here: https://github.com/fiatjaf/rosetta.alhur.es/blob/b05cbdec48d804685db9a61d2b8da82367a6fd19/rosetta.go#L35-L60

I guess it is an issue with the `++`, but it used to work in the past, and also doesn't work with the escaped form, `C%2B%2B`.
