### ISSUE TITLE
About the Perl 6 renamed to Raku

### ISSUE THREAD

**Issue by hkdtam** [fiatjaf/rosetta.alhur.es#8]
Hi fiatjaf,

Thanks for your work and I have spent a lot of great time using the service.

Just to let you know that all the "Perl 6" entries were migrated to "Raku" so if possible please accommodate the change at your time of convenience.

Many thanks in advance.

Regards,
hkdtam.

**Comment by fiatjaf** [comment]
Thank you very much.

**Comment by hkdtam** [comment]
Wow that is prompt, thank you very much.
