### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Doaxan** [fiatjaf/rosetta.alhur.es#9]
I wish rosetta.alhur.es  was online again :smiley:

**Comment by fiatjaf** [comment]
That's glad to hear, I thought it was online, but apparently there is something weird with my Caddy.

**Comment by fiatjaf** [comment]
https://rosetta.fiatjaf.com should be back soon. For now http://rosetta.fiatjaf.com is online.

**Comment by Doaxan** [comment]
This is a pretty useful service for me, thanks a lot!
